"""Write game/sprites.js from assets/sprites/*.json, so the game can load sprite data
without a web server (opening game/index.html straight from disk can't fetch JSON).
usage: python tools/make_manifest.py"""
import glob, json, os

root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
out = {}
for path in sorted(glob.glob(os.path.join(root, "assets", "sprites", "*.json"))):
    name = os.path.basename(path)[:-5]
    d = json.load(open(path))
    out[name] = {
        "src": f"../assets/sprites/{name}.png",
        "frames": d["frames"], "w": d["frame_w"], "h": d["frame_h"],
        "ms": d["ms_per_frame"], "loop": d["loop"], "pingpong": d.get("pingpong", False),
        "ax": d["anchor_x"], "ay": d["anchor_y"], "align": d.get("align", "feet"),
    }
with open(os.path.join(root, "game", "sprites.js"), "w") as f:
    f.write("// Generated by tools/make_manifest.py. Don't edit by hand.\n")
    f.write("window.SPRITE_DATA = " + json.dumps(out, indent=1) + ";\n")
print(f"{len(out)} sprites -> game/sprites.js")
